.Dd February 13, 2022
.Dt FAQ 7
.Os "Causal Agency"
.
.Sh Frequently Asked Questions
This is a compilation of
frequently asked questions
on the cgit mailing list.
.
.Ss Why doesn't cgit find/show my repo?
This is most likely
due to permission problems:
cgit runs under your webserver user account
and will need read access to your repo
(and all of the parent directories).
.
.Ss Why does cgit complain that my repo is not a git repository?
The most common cause of this
is permission problems \(em
see the previous FAQ entry.
.Pp
The second most common cause
is that you've set
.Cm repo.path
to point at the working-directory
of your git repo \(em
it should point at the
.Ev $GITDIR ,
i.e. the
.Pa .git
directory.
.Pp
A less likely cause is that the repo is,
in fact,
not a valid repo.
Try to run
.Ql git show
in the offending repo
to see if git also thinks
your repo has issues.
.
.Ss Why is the idle time for my repository wrong?
By default cgit uses the modification time
of the default branch's ref file
as a quick method of determining
when the repository was last changed.
If you primarily work on other branches
then this work will not be reflected
in the idle time.
.Pp
You can use a post-receive hook
to run a script that tells cgit
the correct modification time
by writing to
.Pa info/web/last-modified .
An example is provided
in the cgit repository at
.Pa contrib/hooks/post-receive.agefile .
