.Dd March 27, 2022
.Dt INDEX 7
.Os "Causal Agency"
.
.Sh NAME
.Nm cgit-pink
.Nd web frontend for git
.
.Sh DESCRIPTION
.Nm
is a fork of cgit.
Upstream cgit has long been stagnant,
with the vast majority of patches
sent to the mailing list
going silently ignored,
despite their obvious merit
in many cases.
This fork aims to incorporate
a number of existing patches
as well as to provide a friendlier place
to send new patches.
They will,
at the very least,
get a reply.
This fork also aims
to make new releases
which can hopefully be picked up
by package repositories,
making it easier for users
to run an improved cgit.
.
.Ss Quick Facts
.Bl -bullet -compact
.It
web interface (CGI) for git repositories, written in C
.It
licensed under GPLv2
.It
discussions, patches, etc. go to
.Aq Mt list+cgit@causal.agency
.Pq Lk https://causal.agency/list/cgit.html archive
.It
real time chat available in
.Li #ascii.town
on
.Li tilde.chat
.It
common questions are answered in the
.Xr faq 7
.El
.
.Ss Features
.Bl -bullet -compact
.It
basic repository browsing (logs, diffs, trees...)
.It
caching of generated HTML
.It
cloneable URLs (implements dumb HTTP transport)
.It
commit feeds (atom format)
.It
discovery of git repositories
.It
on-the-fly archives for tags and commits
.It
plugin support for syntax highlighting
.It
side-by-side diffs
.It
simple time/author statistics
.It
simple virtual hosting support (macro expansion)
.It
understands GitWeb project-lists
.It
understands
.Cm gitweb.owner
in git config files
.El
.
.Ss Source Code
.Bl -bullet -compact
.It
download current or past
.Lk /cgit-pink/refs/tags releases
.It
clone the repo:
.Dl git clone https://git.causal.agency/cgit-pink
.It
see the
.Lk /cgit-pink/tree/README README
for build instructions
.El
.
.Ss Packages
.Bl -bullet -compact
.It
.Lk https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/version-management/cgit/pink.nix nixpkgs
.It
.Lk https://git.causal.agency/ports/tree/OpenBSD/www/cgit-pink/Makefile "OpenBSD (unofficial)"
.El
